[package]
name = "tau-script"
version = "0.1.0"
edition = "2024"

[dependencies]
executor = { path = "executor" }

[workspace]
members = [
    "library/error",
    "library/token",

    "lexer",
    "parser",
    "object",
    "executor",
]
