[package]
name = "tau-script"
version = "0.1.0"
edition = "2024"

[dependencies]
executor = { path = "executor" }

[dev-dependencies]
frontend = { path = "frontend" }
object = { path = "object" }


[workspace]
members = [
    "frontend",
    "frontend/lexer",
    "frontend/parser",
    "frontend/frontend-library",

    "object",
    "object/object-core",
    "object/object-ext",
    "object/object-types",

    "executor",
]
