[package]
name = "tau-script"
version = "0.1.0"
edition = "2024"

[dependencies]
executor = { path = "executor" }

[dev-dependencies]
lexer = { path = "lexer" }
parser = { path = "parser" }
object = { path = "object" }
token = { path = "library/token" }


[workspace]
members = [
    "library/error",
    "library/token",
    "library/stream",

    "lexer",
    "parser",

    "executor",

    "object",
    "object/object-core",
    "object/object-ext",
    "object/object-types",
]
